server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            - After=2024-04-05T12:17:09.901804100+08:00[Asia/Shanghai]
#            - Before=2024-04-05T12:19:09.901804100+08:00[Asia/Shanghai]
#            - Between=
#              2024-04-05T12:21:09.901804100+08:00[Asia/Shanghai],
#              2024-04-05T12:26:09.901804100+08:00[Asia/Shanghai]
#            - Cookie=username,qsx
#            - Header=X-Request-ID,\d+ # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com
#            - Query=username,\d+ # 要有参数名username并且值还要是整数才能路由
            - RemoteAddr=192.168.0.1/24

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由